version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo Installing dependencies...
      - npm install

  build:
    commands:
      - echo Packaging the application...
      - zip -r app.zip . # Create a zip file of the app

artifacts:
  files:
    - app.zip